secrets:
  mongo-user: ./secrets/mongo_user
  mongo-pw: ./secrets/mongo_pw


services:
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME_File=/run/secrets/mongo-user
      - MONGO_INITDB_ROOT_PASSWORD_File=/run/secrets/mongo-pw
    volumes:
      - ./DB/data:/data/db
  
  Forntend:
    build:
      context: angular
      target: builder
    volumes:
      - Forntend:/project
      - /project/node_modules
    
  Backend:
    
