/**
 * Digital Forms
 * API For...
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormSection } from './formSection';
import { Attachment } from './attachment';


export interface Form { 
    id?: string;
    template?: boolean;
    titel?: string;
    description?: string;
    category?: Form.CategoryEnum;
    form?: Array<FormSection>;
    attachments?: Array<Attachment>;
}
export namespace Form {
    export type CategoryEnum = 'Antrag' | 'Abrechnung';
    export const CategoryEnum = {
        Antrag: 'Antrag' as CategoryEnum,
        Abrechnung: 'Abrechnung' as CategoryEnum
    };
}


