/**
 * Digital Forms
 * API For...
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FormElement } from './formElement';


export interface FormSection { 
    order?: number;
    section?: string;
    items?: Array<FormElement>;
}

