/**
 * Digital Forms
 * API For...
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FormElement { 
    id?: string;
    Description?: string;
    help?: string;
    type?: FormElement.TypeEnum;
}
export namespace FormElement {
    export type TypeEnum = 'text' | 'address' | 'iban' | 'date' | 'money' | 'TextMultiLine' | 'bool';
    export const TypeEnum = {
        Text: 'text' as TypeEnum,
        Address: 'address' as TypeEnum,
        Iban: 'iban' as TypeEnum,
        Date: 'date' as TypeEnum,
        Money: 'money' as TypeEnum,
        TextMultiLine: 'TextMultiLine' as TypeEnum,
        Bool: 'bool' as TypeEnum
    };
}


