openapi: 3.0.3
info:
  title: Digital Forms
  description: |-
    API For...
  license:
    name: GPL v3
  version: 0.0.2
servers:
  - url: https://backend.df.dk4max.com/api/v3
  - url: http://localhost:8080/api/v3

paths:
  /templates:
    get:
      summary: Get all Templats
      description: Returns all templates
      security:
        - BearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Form"
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'


  /templates/{templateId}:
    get:
      summary: Find Template by ID
      description: Returns a single Template
      security:
        - BearerAuth: []
      parameters:
        - name: templateId
          in: path
          description: ID of Template to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Form"
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
        '404':
          description: Template not found
  
  /forms:
    get:
      tags:
        - forms
      summary: Get all Forms
      description: Returns all Forms for the requesting User
      security:
        - BearerAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Form"
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
    post:
      tags:
        - forms
      summary: Save a new Form
      description: Save a new Form for the requesting User
      security:
        - BearerAuth: []
      responses:
        '201':
          description: successful Creation with ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Form"
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
        '400':
          description: Invalid Data
  
  /forms/{formID}:
    get:
      tags:
        - forms
      summary: Get the formdata by ID
      description: Get the Data for a Form by ID for the requesting User
      security:
        - BearerAuth: []
      parameters:
        - name: formID
          in: path
          description: ID of form to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Form"
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
        '404':
          description: Form not found
    put:
      tags:
        - forms
      summary: Update a Form by ID
      description: Update a Form by ID for the requesting User
      parameters:
        - name: formID
          in: path
          description: ID of form to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Form"
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
        '400':
          description: Invalid Data
    delete:
      tags:
        - forms
      summary: delete a Form by ID
      description: delete a Form by ID for the requesting User
      parameters:
        - name: formID
          in: path
          description: ID of form to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
        '404':
          description: Can't find ID





components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT  # Optional, but useful for documentation
  headers:
    Access-Control-Allow-Origin:
      description: Specifies which origins are allowed to access the resource.
      schema:
        type: string
      examples:
        localhost:
          summary: Local development environment
          value: http://localhost:4200
        production:
          summary: Production environment
          value: https://df.dk4max.com
  schemas:
    FormElement:
      type: "object"
      properties:
        id:
          type: "string"
        Description:
          type: "string"
        help:
          type: "string"
        type:
          type: "string"
          enum:
            - "text"
            - "address"
            - "iban"
            - "date"
            - "money"
            - "TextMultiLine"
            - "bool"
        value:
          type: "string"
    FormSection:
      type: "object"
      properties:
        order:
          type: "integer"
          format: "int32"
        section:
          type: "string"
        items:
          type: "array"
          items:
            $ref: "#/components/schemas/FormElement"
    Attachment:
      type: "object"
      properties:
        id:
          type: "string"
        description:
          type: "string"
    Form:
      type: "object"
      properties:
        id:
          type: "string"
        owner:
          type: "string"
        template:
          type: "boolean"
        titel:
          type: "string"
        description:
          type: "string"
        category:
          type: "string"
          enum:
            - "Antrag"
            - "Abrechnung"
        form:
          type: "array"
          items:
            $ref: "#/components/schemas/FormSection"
        attachments:
          type: "array"
          items:
            $ref: "#/components/schemas/Attachment"
security:
  - BearerAuth: []
