openapi: 3.0.3
info:
  title: Digital Forms
  description: |-
    API For...
  license:
    name: GPL v3
  version: 0.0.1
servers:
  - url: https://backend.df.dk4max.com/api/v3
  - url: http://localhost:8080/api/v3

paths:
  /templates:
    get:
      summary: Get all Templats
      description: Returns all templates
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Form"
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'


  /templates/{templateId}:
    get:
      summary: Find Template by ID
      description: Returns a single Template
      parameters:
        - name: templateId
          in: path
          description: ID of Template to return
          required: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Form"
          headers:
            Access-Control-Allow-Origin:
              $ref: '#/components/headers/Access-Control-Allow-Origin'
        '404':
          description: Template not found

components:
  headers:
    Access-Control-Allow-Origin:
      description: Specifies which origins are allowed to access the resource.
      schema:
        type: string
      examples:
        localhost:
          summary: Local development environment
          value: http://localhost:4200
        production:
          summary: Production environment
          value: https://df.dk4max.com
  schemas:
    FormElement:
      type: "object"
      properties:
        id:
          type: "string"
        Description:
          type: "string"
        help:
          type: "string"
        type:
          type: "string"
          enum:
            - "text"
            - "address"
            - "iban"
            - "date"
            - "money"
            - "TextMultiLine"
            - "bool"
    FormSection:
      type: "object"
      properties:
        order:
          type: "integer"
          format: "int32"
        section:
          type: "string"
        items:
          type: "array"
          items:
            $ref: "#/components/schemas/FormElement"
    Attachment:
      type: "object"
      properties:
        id:
          type: "string"
        description:
          type: "string"
    Form:
      type: "object"
      properties:
        id:
          type: "string"
        template:
          type: "boolean"
        titel:
          type: "string"
        description:
          type: "string"
        category:
          type: "string"
          enum:
            - "Antrag"
            - "Abrechnung"
        form:
          type: "array"
          items:
            $ref: "#/components/schemas/FormSection"
        attachments:
          type: "array"
          items:
            $ref: "#/components/schemas/Attachment"